# Generated by Django 4.2.7 on 2023-11-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(max_length=10000)),
                ('date_t', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('NORM', 'Normal'), ('LOW', 'low')], default='HIGH', max_length=4)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.patient')),
            ],
        ),
    ]
