# Generated by Django 4.2.7 on 2023-11-27 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0003_rename_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('NORM', 'Normal'), ('LOW', 'Low')], default='HIGH', max_length=4),
        ),
    ]
